# Generated by Django 5.2.12 on 2026-03-27 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="crm_base_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="conversation",
            name="crm_bound_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="crm_customer_record_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="conversation",
            name="crm_customer_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="conversation",
            name="crm_last_writeback_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="crm_last_writeback_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="conversation",
            name="crm_opportunity_record_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="conversation",
            name="crm_opportunity_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="conversation",
            name="crm_provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["crm_customer_record_id"], name="conversatio_crm_cus_bcfd11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["crm_opportunity_record_id"],
                name="conversatio_crm_opp_da377e_idx",
            ),
        ),
    ]
