# Generated by Django 5.2.12 on 2026-03-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_archived_at_user_archived_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="feishu_department_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="department",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="sync_source",
            field=models.CharField(
                choices=[("platform", "Platform"), ("feishu", "Feishu")],
                default="platform",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="feishu_open_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="feishu_union_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="feishu_user_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_external_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sync_source",
            field=models.CharField(
                choices=[("platform", "Platform"), ("feishu", "Feishu")],
                default="platform",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("synced", "Synced"),
                    ("stale", "Stale"),
                    ("disabled", "Disabled"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
    ]
