# Generated by Django 5.2.12 on 2026-03-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_department_feishu_department_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feishu_personal_task_auth_status",
            field=models.CharField(default="unbound", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="feishu_personal_task_authorized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="feishu_user_access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="feishu_user_refresh_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="feishu_user_refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="feishu_user_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
