# Generated by Django 5.2.12 on 2026-03-22 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_user_archived_at_user_archived_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDemandSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("session_title", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("customer_type", models.CharField(blank=True, max_length=50)),
                ("knowledge_enabled", models.BooleanField(default=False)),
                ("knowledge_scope", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("recording", "Recording"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("recording_started_at", models.DateTimeField(blank=True, null=True)),
                ("recording_stopped_at", models.DateTimeField(blank=True, null=True)),
                ("analysis_started_at", models.DateTimeField(blank=True, null=True)),
                ("analysis_finished_at", models.DateTimeField(blank=True, null=True)),
                ("raw_segment_count", models.PositiveIntegerField(default=0)),
                ("normalized_segment_count", models.PositiveIntegerField(default=0)),
                ("latest_stage_version", models.PositiveIntegerField(default=0)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_demand_sessions",
                        to="accounts.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_demand_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDemandSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_no", models.PositiveIntegerField()),
                ("speaker_label", models.CharField(blank=True, max_length=32)),
                ("raw_text", models.TextField(blank=True)),
                ("normalized_text", models.TextField(blank=True)),
                ("final_text", models.TextField(blank=True)),
                ("asr_provider", models.CharField(blank=True, max_length=50)),
                ("llm_provider", models.CharField(blank=True, max_length=50)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "semantic_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("review_flag", models.BooleanField(default=False)),
                ("issues_json", models.JSONField(blank=True, default=list)),
                ("raw_start_ms", models.BigIntegerField(blank=True, null=True)),
                ("raw_end_ms", models.BigIntegerField(blank=True, null=True)),
                (
                    "segment_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("asr_ready", "AsrReady"),
                            ("normalized", "Normalized"),
                            ("review_required", "ReviewRequired"),
                            ("discarded", "Discarded"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="customer_demand.customerdemandsession",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_no", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDemandReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_version", models.PositiveIntegerField()),
                ("report_title", models.CharField(max_length=255)),
                ("report_markdown", models.TextField(blank=True)),
                ("report_html", models.TextField(blank=True)),
                ("report_payload", models.JSONField(blank=True, default=dict)),
                ("digging_suggestions_markdown", models.TextField(blank=True)),
                (
                    "digging_suggestions_payload",
                    models.JSONField(blank=True, default=dict),
                ),
                ("recommended_questions_markdown", models.TextField(blank=True)),
                ("knowledge_enabled", models.BooleanField(default=False)),
                ("used_knowledge_sources", models.JSONField(blank=True, default=list)),
                ("llm_model", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customer_demand_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="customer_demand.customerdemandsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_version", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDemandParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("sales", "Sales"),
                            ("presales", "PreSales"),
                            ("tech_support", "TechSupport"),
                            ("project_manager", "ProjectManager"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("speaker_label", models.CharField(blank=True, max_length=32)),
                ("is_internal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="customer_demand.customerdemandsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDemandAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                ("storage_path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_customer_demand_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="customer_demand.customerdemandsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDemandAnalysisTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("stage_summary", "StageSummary"),
                            ("final_analysis", "FinalAnalysis"),
                            ("export_report", "ExportReport"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=100)),
                ("current_step_label", models.CharField(blank=True, max_length=100)),
                ("progress", models.PositiveIntegerField(default=0)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_customer_demand_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_tasks",
                        to="customer_demand.customerdemandsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDemandStageSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary_version", models.PositiveIntegerField()),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("auto_interval", "AutoInterval"),
                            ("auto_segment_threshold", "AutoSegmentThreshold"),
                            ("manual", "Manual"),
                            ("session_end", "SessionEnd"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("covered_segment_start", models.PositiveIntegerField(default=1)),
                ("covered_segment_end", models.PositiveIntegerField(default=1)),
                ("summary_markdown", models.TextField(blank=True)),
                ("summary_payload", models.JSONField(blank=True, default=dict)),
                ("llm_model", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customer_demand_stage_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_summaries",
                        to="customer_demand.customerdemandsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-summary_version", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customerdemandsession",
            index=models.Index(
                fields=["owner", "-updated_at"], name="customer_de_owner_i_45edff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerdemandsession",
            index=models.Index(
                fields=["department", "-updated_at"],
                name="customer_de_departm_eda8f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerdemandsession",
            index=models.Index(
                fields=["status", "-updated_at"], name="customer_de_status_312f06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerdemandsession",
            index=models.Index(
                fields=["customer_name"], name="customer_de_custome_6b50bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerdemandsession",
            index=models.Index(
                fields=["industry"], name="customer_de_industr_81956e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerdemandsession",
            index=models.Index(fields=["region"], name="customer_de_region_bf004b_idx"),
        ),
        migrations.AddIndex(
            model_name="customerdemandsegment",
            index=models.Index(
                fields=["session", "sequence_no"], name="customer_de_session_6fbf25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerdemandsegment",
            index=models.Index(
                fields=["session", "created_at"], name="customer_de_session_34b4ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerdemandsegment",
            index=models.Index(
                fields=["review_flag"], name="customer_de_review__f7538e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerdemandsegment",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence_no"),
                name="uniq_customer_demand_segment_seq",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerdemandreport",
            constraint=models.UniqueConstraint(
                fields=("session", "report_version"),
                name="uniq_customer_demand_report_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerdemandstagesummary",
            constraint=models.UniqueConstraint(
                fields=("session", "summary_version"),
                name="uniq_customer_demand_summary_version",
            ),
        ),
    ]
