# Generated by Django 5.2.12 on 2026-03-27 01:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmWritebackRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("feishu_bitable", "FeishuBitable")],
                        default="feishu_bitable",
                        max_length=32,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("customer_demand_session", "CustomerDemandSession"),
                            ("customer_demand_report", "CustomerDemandReport"),
                            ("solution_conversation", "SolutionConversation"),
                            ("solution_result", "SolutionResult"),
                            ("presales_task", "PresalesTask"),
                            ("archive_record", "ArchiveRecord"),
                        ],
                        max_length=64,
                    ),
                ),
                ("object_id", models.CharField(max_length=128)),
                (
                    "target_table",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("opportunity", "Opportunity"),
                            ("followup", "Followup"),
                            ("attachment", "Attachment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_record_id", models.CharField(blank=True, max_length=128)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("bind", "Bind"),
                            ("create_record", "CreateRecord"),
                            ("update_record", "UpdateRecord"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_writeback_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id", "created_at"],
                        name="crm_integra_object__f383e9_idx",
                    ),
                    models.Index(
                        fields=["target_table", "status", "created_at"],
                        name="crm_integra_target__7edd2a_idx",
                    ),
                    models.Index(
                        fields=["provider", "created_at"],
                        name="crm_integra_provide_80db19_idx",
                    ),
                ],
            },
        ),
    ]
