# Generated by Django 5.2.12 on 2026-03-23 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_user_archived_at_user_archived_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeishuDeliveryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_type", models.CharField(max_length=64)),
                ("business_id", models.CharField(blank=True, max_length=128)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("group", "Group"),
                            ("department_owner", "DepartmentOwner"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_id", models.CharField(max_length=128)),
                ("target_name", models.CharField(blank=True, max_length=255)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("post", "Post"),
                            ("interactive_card", "InteractiveCard"),
                        ],
                        default="text",
                        max_length=32,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presales_feishu_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeishuSyncJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("sync_departments", "SyncDepartments"),
                            ("sync_users", "SyncUsers"),
                            ("full_sync", "FullSync"),
                            ("offboarding_reconcile", "OffboardingReconcile"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                            ("startup", "Startup"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("synced_user_count", models.PositiveIntegerField(default=0)),
                ("synced_department_count", models.PositiveIntegerField(default=0)),
                ("disabled_user_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("summary_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presales_feishu_sync_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PresalesArchiveRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "archive_type",
                    models.CharField(
                        choices=[
                            ("meeting_recording", "MeetingRecording"),
                            ("demand_report", "DemandReport"),
                            ("stage_summary", "StageSummary"),
                            ("solution_markdown", "SolutionMarkdown"),
                            ("solution_html", "SolutionHtml"),
                            ("solution_pdf", "SolutionPdf"),
                            ("attachment", "Attachment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_type", models.CharField(max_length=64)),
                ("source_id", models.CharField(blank=True, max_length=128)),
                ("source_version", models.PositiveIntegerField(blank=True, null=True)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("source_title", models.CharField(max_length=255)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                (
                    "storage_provider",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("s3", "S3"),
                            ("oss", "OSS"),
                            ("cos", "COS"),
                        ],
                        default="local",
                        max_length=32,
                    ),
                ),
                ("storage_path", models.CharField(max_length=500)),
                ("storage_bucket", models.CharField(blank=True, max_length=128)),
                (
                    "archive_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deleted", "Deleted"),
                            ("orphaned", "Orphaned"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("feishu_shared", models.BooleanField(default=False)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_presales_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PresalesTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_title", models.CharField(max_length=255)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("follow_up", "FollowUp"),
                            ("proposal_review", "ProposalReview"),
                            ("customer_revisit", "CustomerRevisit"),
                            ("internal_alignment", "InternalAlignment"),
                            ("materials_prepare", "MaterialsPrepare"),
                            ("manual", "Manual"),
                        ],
                        default="follow_up",
                        max_length=32,
                    ),
                ),
                ("task_description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("customer_demand_report", "CustomerDemandReport"),
                            ("solution_result", "SolutionResult"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=64,
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=128)),
                ("source_version", models.PositiveIntegerField(blank=True, null=True)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_id", models.CharField(blank=True, max_length=128)),
                ("collaborator_user_ids", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "InProgress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("reassigned", "Reassigned"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                (
                    "followup_status",
                    models.CharField(
                        choices=[
                            ("not_scheduled", "NotScheduled"),
                            ("scheduled", "Scheduled"),
                            ("done", "Done"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_scheduled",
                        max_length=32,
                    ),
                ),
                (
                    "feishu_delivery_status",
                    models.CharField(
                        choices=[
                            ("not_sent", "NotSent"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="not_sent",
                        max_length=32,
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_presales_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_presales_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "latest_feishu_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="latest_for_tasks",
                        to="presales_center.feishudeliveryrecord",
                    ),
                ),
                (
                    "owner_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_presales_tasks",
                        to="accounts.department",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_presales_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PresalesFollowupReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("task_due", "TaskDue"),
                            ("task_overdue", "TaskOverdue"),
                            ("follow_up", "FollowUp"),
                            ("manual", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("superseded", "Superseded"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("feishu", "Feishu"), ("platform", "Platform")],
                        default="feishu",
                        max_length=32,
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "latest_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_latest_for",
                        to="presales_center.feishudeliveryrecord",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presales_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="presales_center.presalestask",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PresalesTaskActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("assigned", "Assigned"),
                            ("status_changed", "StatusChanged"),
                            ("due_changed", "DueChanged"),
                            ("followup_scheduled", "FollowupScheduled"),
                            ("followup_completed", "FollowupCompleted"),
                            ("feishu_sent", "FeishuSent"),
                            ("feishu_failed", "FeishuFailed"),
                            ("archive_created", "ArchiveCreated"),
                            ("reassigned", "Reassigned"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=32)),
                ("to_status", models.CharField(blank=True, max_length=32)),
                ("summary", models.CharField(max_length=255)),
                ("details_markdown", models.TextField(blank=True)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presales_task_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="presales_center.presalestask",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="feishudeliveryrecord",
            index=models.Index(
                fields=["business_type", "business_id"],
                name="presales_ce_busines_62df60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feishudeliveryrecord",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="presales_ce_target__5fbaba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feishudeliveryrecord",
            index=models.Index(
                fields=["delivery_status", "created_at"],
                name="presales_ce_deliver_aef913_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feishudeliveryrecord",
            index=models.Index(
                fields=["operator_user", "created_at"],
                name="presales_ce_operato_6ad2cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feishusyncjob",
            index=models.Index(
                fields=["job_type", "created_at"], name="presales_ce_job_typ_dd6828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feishusyncjob",
            index=models.Index(
                fields=["status", "created_at"], name="presales_ce_status_2cd871_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feishusyncjob",
            index=models.Index(
                fields=["trigger_type", "created_at"],
                name="presales_ce_trigger_a633cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalesarchiverecord",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="presales_ce_source__fb6edc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalesarchiverecord",
            index=models.Index(
                fields=["archive_type", "created_at"],
                name="presales_ce_archive_45f39d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalesarchiverecord",
            index=models.Index(
                fields=["customer_name", "created_at"],
                name="presales_ce_custome_a683a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalesarchiverecord",
            index=models.Index(
                fields=["archive_status", "updated_at"],
                name="presales_ce_archive_db140e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalestask",
            index=models.Index(
                fields=["assignee_user", "status", "due_at"],
                name="presales_ce_assigne_bdbdbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalestask",
            index=models.Index(
                fields=["owner_department", "status", "created_at"],
                name="presales_ce_owner_d_eef640_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalestask",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="presales_ce_source__cf9d30_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalestask",
            index=models.Index(
                fields=["customer_name", "created_at"],
                name="presales_ce_custome_260d99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalestask",
            index=models.Index(
                fields=["next_follow_up_at", "followup_status"],
                name="presales_ce_next_fo_b14638_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalestask",
            index=models.Index(
                fields=["feishu_delivery_status", "updated_at"],
                name="presales_ce_feishu__d877c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalesfollowupreminder",
            index=models.Index(
                fields=["scheduled_at", "status"], name="presales_ce_schedul_99243e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presalesfollowupreminder",
            index=models.Index(
                fields=["target_user", "status"], name="presales_ce_target__09c7a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presalesfollowupreminder",
            index=models.Index(
                fields=["task", "reminder_type"], name="presales_ce_task_id_8d0980_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presalestaskactivity",
            index=models.Index(
                fields=["task", "created_at"], name="presales_ce_task_id_279d4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presalestaskactivity",
            index=models.Index(
                fields=["activity_type", "created_at"],
                name="presales_ce_activit_4c494b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalestaskactivity",
            index=models.Index(
                fields=["operator_user", "created_at"],
                name="presales_ce_operato_468648_idx",
            ),
        ),
    ]
