# Generated by Django 5.2.12 on 2026-03-25 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presales_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presalestaskactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("assigned", "Assigned"),
                    ("status_changed", "StatusChanged"),
                    ("due_changed", "DueChanged"),
                    ("followup_scheduled", "FollowupScheduled"),
                    ("followup_completed", "FollowupCompleted"),
                    ("feishu_sent", "FeishuSent"),
                    ("feishu_failed", "FeishuFailed"),
                    ("feishu_task_created", "FeishuTaskCreated"),
                    ("archive_created", "ArchiveCreated"),
                    ("reassigned", "Reassigned"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="FeishuTaskRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operator_identity_key", models.CharField(max_length=128)),
                ("operator_open_id", models.CharField(blank=True, max_length=128)),
                ("operator_user_id", models.CharField(blank=True, max_length=128)),
                ("operator_name", models.CharField(blank=True, max_length=255)),
                ("feishu_task_id", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Created"), ("failed", "Failed")],
                        default="created",
                        max_length=32,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "presales_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feishu_task_records",
                        to="presales_center.presalestask",
                    ),
                ),
                (
                    "source_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feishu_tasks",
                        to="presales_center.feishudeliveryrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["presales_task", "created_at"],
                        name="presales_ce_presale_6b35ef_idx",
                    ),
                    models.Index(
                        fields=["operator_identity_key", "created_at"],
                        name="presales_ce_operato_2b2fbe_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="presales_ce_status_7bc47d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("presales_task", "operator_identity_key"),
                        name="presales_feishu_task_unique_operator",
                    )
                ],
            },
        ),
    ]
