# Generated by Django 5.2.12 on 2026-03-27 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_feishu_personal_task_auth_status_and_more"),
        ("presales_center", "0002_alter_presalestaskactivity_activity_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="presalesarchiverecord",
            name="crm_base_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="presalesarchiverecord",
            name="crm_bound_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presalesarchiverecord",
            name="crm_customer_record_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="presalesarchiverecord",
            name="crm_customer_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="presalesarchiverecord",
            name="crm_last_writeback_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presalesarchiverecord",
            name="crm_last_writeback_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="presalesarchiverecord",
            name="crm_opportunity_record_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="presalesarchiverecord",
            name="crm_opportunity_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="presalesarchiverecord",
            name="crm_provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="presalestask",
            name="crm_base_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="presalestask",
            name="crm_bound_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presalestask",
            name="crm_customer_record_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="presalestask",
            name="crm_customer_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="presalestask",
            name="crm_last_writeback_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presalestask",
            name="crm_last_writeback_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="presalestask",
            name="crm_opportunity_record_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="presalestask",
            name="crm_opportunity_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="presalestask",
            name="crm_provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="feishutaskrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("created", "Created"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="presalesarchiverecord",
            index=models.Index(
                fields=["crm_customer_record_id"], name="presales_ce_crm_cus_f6c0a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presalesarchiverecord",
            index=models.Index(
                fields=["crm_opportunity_record_id"],
                name="presales_ce_crm_opp_a32822_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="presalestask",
            index=models.Index(
                fields=["crm_customer_record_id"], name="presales_ce_crm_cus_30d65d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presalestask",
            index=models.Index(
                fields=["crm_opportunity_record_id"],
                name="presales_ce_crm_opp_ac17c0_idx",
            ),
        ),
    ]
